name: Deploy to Upstream Environment ###############
on:
  push:
    branches: [main, dev]
  pull_request_target:
    types: [assigned, opened, edited, synchronize, reopened]
    branches: [main, dev]
    
  workflow_dispatch:
    inputs:
      envSelection:
        description: 'Select Environment to Deploy'
        default: 'Select from the List'
        required: true
        type: choice
        options:
        - 'Select from the List'
        - 'Deploy To TST'
        - 'Deploy To ACC'
        - 'Deploy To PRD' 
      envName:
        description: 'Enter env name manually (tst / acc / prd)'
        required: true 
        type: string
      buildNumber:
        description: 'Enter Build Number'
        required: true 
        type: number
env:
  MY_NAME: 'Kundan'
jobs:
  print-tag:
    runs-on: ubuntu-latest
    if: true #inputs.envSelection != 'Select from the List'
    steps:
      - name: Values entered= ${{ inputs.envName }}
        run: |
             echo Env to deploy=  ${{ inputs.envSelection }} 
             echo Env to deploy= ${{ inputs.envName }} 
             echo Build No= ${{ inputs.buildNumber }}, ${{ inputs.envSelection == 'Deploy To TST' }} 
      - if: inputs.envSelection == 'Deploy To TST' && inputs.envName == 'tst' 
        name: Print the input to STDOUT
        run: echo  The values entered are  ${{ inputs.envSelection }} , ${{ inputs.envName }} , ${{ inputs.buildNumber }}, ${{ inputs.envSelection == 'Deploy To TST' }} 
      - if: inputs.envSelection == 'Deploy To ACC' && inputs.envName == 'acc'
        env:
          MY_NAME: 'Kundan-${{ inputs.envName }}'
        name: Print the input to STDOUT
        run: echo  The values entered are  ${{ inputs.envSelection }} , ${{ inputs.envName }} , ${{ inputs.buildNumber }}, ${{ inputs.envSelection == 'Deploy To ACC' }} 
      - if: inputs.envSelection == 'Deploy To PRD' && inputs.envName == 'prd' 
        env:
          MY_NAME: 'Kundan-${{ inputs.envName }}'
        name: Print the input to STDOUT
        run: echo  The values entered are  ${{ inputs.envSelection }} , ${{ inputs.envName }} , ${{ inputs.buildNumber }}, ${{ inputs.envSelection == 'Deploy To PRD' }}
      
      - name: 'CHeck env'
        run: |
             if [ ${{ inputs.envName }}  == 'tst' ]; 
             then
               echo It is tst
             else
               echo It is anything else
             fi
        shell: bash
      - run: |
          echo "event_name comparision value=" ${{ github.event_name != 'pull_request_target' }}
        
  run_if:
    if:  ${{ github.event_name != 'pull_request_target' }}
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
             echo "ref=" ${{ github.ref }}
             echo "base_ref=" ${{ github.base_ref }}
             echo "github event_name=" ${{ github.event_name }}
             echo "event.pull_request.marged=" ${{ github.event.pull_request.merged }}
             echo "event.pull_request_target.marged=" ${{ github.event.pull_request_target.merged }}
             echo "$GITHUB_CONTEXT"
  check_buildah:
    runs-on: ubuntu-latest
    env:
      runner_image:  quay.io/redhat-github-actions/buildah-runner
    steps:
      - run: java -version
      - run: mvn -version
      - run: docker --version
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java -version
      - run: mvn -version
      - run: docker --version
     
