name: Deploy to Upstream Environment
on:
  workflow_dispatch:
    inputs:
      envSelection:
        description: 'Select Environment to Deploy'
        default: 'Select from the List'
        required: true
        type: choice
        options:
        - 'Select from the List'
        - 'Deploy To TST'
        - 'Deploy To ACC'
        - 'Deploy To PRD' 
      envName:
        description: 'Enter env name manually (tst / acc / prd)'
        required: true 
        type: string
      buildNumber:
        description: 'Enter Build Number'
        required: true 
        type: number
jobs:
  print-tag:
    runs-on: ubuntu-latest
    if: inputs.envSelection != 'Select from the List'
    steps:
      - name: Values entered
        run: echo  The values entered are  ${{ inputs.envSelection }} , ${{ inputs.envName }} , ${{ inputs.buildNumber }}, ${{ inputs.envSelection == 'Deploy To TST' }} 
      - if: inputs.envSelection == 'Deploy To TST' && inputs.envName == 'tst' 
        name: Print the input to STDOUT
        run: echo  The values entered are  ${{ inputs.envSelection }} , ${{ inputs.envName }} , ${{ inputs.buildNumber }}, ${{ inputs.envSelection == 'Deploy To TST' }} 
      - if: inputs.envSelection == 'Deploy To ACC' && inputs.envName == 'acc'
        name: Print the input to STDOUT
        run: echo  The values entered are  ${{ inputs.envSelection }} , ${{ inputs.envName }} , ${{ inputs.buildNumber }}, ${{ inputs.envSelection == 'Deploy To ACC' }} 
      - if: inputs.envSelection == 'Deploy To PRD' && inputs.envName == 'prd' 
        name: Print the input to STDOUT
        run: echo  The values entered are  ${{ inputs.envSelection }} , ${{ inputs.envName }} , ${{ inputs.buildNumber }}, ${{ inputs.envSelection == 'Deploy To PRD' }} 
